### ISSUE TITLE
android-actionbar的submodule仓库不存在了

### ISSUE THREAD

**Issue by Juude** [mingcheng/Tracker#11]
提示错误： 

fatal: repository 'https://github.com/dodocat/android-actionbar.git/' not found
fatal: clone of 'https://github.com/dodocat/android-actionbar.git' into submodule path '/Users/juude/git/Tracker/libraries/android-actionbar' failed

**Comment by mingcheng** [comment]
项目比较老了，建议直接用官方提供的兼容包
